## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
for data in [datasets.load_boston(),datasets.load_breast_cancer(),datasets.load_diabetes(),datasets.load_digits(),datasets.load_iris()]:
    for model in [linear_model.LinearRegression(),linear_model.Lasso(alpha=0.1),linear_model.Lasso(alpha=1.0),linear_model.Lasso(alpha=2.0),linear_model.Ridge(alpha=0.1),linear_model.Ridge(alpha=1.0),linear_model.Ridge(alpha=2.0)]:
        print("-"*6,data['DESCR'].splitlines()[0],"shape is",data.data.shape,"-"*6,type(model).__name__,"alpha is",model.get_params().get('alpha'))
        x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=4)
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        print(model.coef_)
        print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

------ .. _boston_dataset: shape is (506, 13) ------ LinearRegression alpha is None
[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]
Mean squared error: 25.42
------ .. _boston_dataset: shape is (506, 13) ------ Lasso alpha is 0.1
[-0.10618872  0.04886351 -0.04536655  1.14953069 -0.          3.82353877
 -0.02089779 -1.23590613  0.26008876 -0.01517094 -0.74673362  0.00963864
 -0.49877104]
Mean squared error: 26.45
------ .. _boston_dataset: shape is (506, 13) ------ Lasso alpha is 1.0
[-0.06494981  0.04581458 -0.          0.         -0.          1.18140024
  0.01109101 -0.73695809  0.23350042 -0.01551065 -0.69270805  0.00763157
 -0.6927848 ]
Mean squared error: 28.95
------ .. _boston_dataset: shape is (506, 13) ------ Lasso alpha is 2.0
[-0.0181519   0.03043393 -0.          0.         -0.          0.
  0.03717309 -0.12778153

------ .. _iris_dataset: shape is (150, 4) ------ Lasso alpha is 2.0
[ 0. -0.  0.  0.]
Mean squared error: 0.86
------ .. _iris_dataset: shape is (150, 4) ------ Ridge alpha is 0.1
[-0.13328295 -0.04292389  0.24239954  0.59250241]
Mean squared error: 0.05
------ .. _iris_dataset: shape is (150, 4) ------ Ridge alpha is 1.0
[-0.13202176 -0.03444754  0.27117435  0.52316571]
Mean squared error: 0.05
------ .. _iris_dataset: shape is (150, 4) ------ Ridge alpha is 2.0
[-0.12498751 -0.03188605  0.28953795  0.47099988]
Mean squared error: 0.05
